<?php

namespace rm\EmailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function finAllCategorieByUser($userId)
	{
		$qb = $this->createQueryBuilder('c')
				   ->select('c')
				   ->leftJoin('c.user', 'u')
				   ->where('u.id = :uid')
				   ->setParameter('uid', $userId);				   		   

		return $qb;
	}
}
