<?php

namespace rm\EmailBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
	public function calculteNumEmailsByCat($id){
		$qb = $this->createQueryBuilder('e')
				   ->select('COUNT(e)')
				   ->leftJoin('e.categories','c')
				   ->where('c.id = :id')
				   ->setParameter('id', $id);

		return $qb->getQuery()
				  ->getSingleScalarResult();
	}

	public function findWhereCategories($id)
	{
		$qb = $this->createQueryBuilder('e')
				   ->leftJoin('e.categories','c')
				   ->where('c.id = :id')
				   ->setParameter('id', $id);

		return $qb->getQuery()
				  ->getResult();
	}
}
