parameters:
#    rm_email.example.class: rm\EmailBundle\Example

services:
#    rm_email.example:
#        class: %rm_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
